### ISSUE TITLE
ppm无法正确解析

### ISSUE THREAD

**Issue by abc1763613206** [quank123wip/ppmanalyzer#1]
已经通过了搜索引擎寻找解决方案
以下是报错信息      
![qb awudh1avngsl8r63 wf7](https://user-images.githubusercontent.com/30773956/50547622-43866200-0c78-11e9-8583-90d66b56ddf0.png)             
另外将读入方式中的"r"改为"rb"仍然无效。       

问题文件：
[Free-Converter.com-task1-78163534.zip](https://github.com/quank123wip/ppmanalyzer/files/2717173/Free-Converter.com-task1-78163534.zip)

**Comment by quank123wip** [comment]
Get,Fixing

**Comment by quank123wip** [comment]
Fixed

**Comment by quank123wip** [comment]
Remenber,use ascii format and use gimp to convert

**Comment by quank123wip** [comment]
Remember,use ascii format and use gimp to convert
